from time import sleep
pessoas = int(input('Quantas Pessoas? '))
preço = float(input('Qual Preço? '))
print('Carregando...')
faturamento = pessoas * preço
sleep(3)
print('O total orçado fica em {:.2f}R$! o valor parcelado em 3x fica {:.2f} em 6x fica {:.2f} em 10x fica {:.2f}R$.'.format(faturamento,(faturamento/3),(faturamento/6),(faturamento/10)))
print('---'*25)
print('Vamos continuar? ...')
sleep(2)
b1 = int(input('Quantos % vão para drinks tradicionais? '))
sleep(1)
b2 = int(input('Quantos % vão para drinks de batidas? '))
sleep(1)
b3 = int(input('Quantos % vão para drinks personalizados? '))
sleep(1)
print('Carregando...')
sleep(3)
print('---'*35)
sleep(2)
print('Do total orçado no valor {}R$, vão ficar {}R$ para drinks tradicionais, {}R$ para drinks de batidas, {}R$ para drinks personalizados'.format(faturamento,(faturamento*(b1/100)),(faturamento*(b2/100)),(faturamento*(b3/100))))